# Generated by Django 3.2.5 on 2021-07-17 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_auto_20210717_1542'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart_id', 'product_id')},
        ),
    ]
