# Generated by Django 3.2.5 on 2021-07-17 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='product_id',
            new_name='product',
        ),
    ]
