# Generated by Django 3.2.5 on 2021-07-17 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_auto_20210717_1545'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together={('order_id', 'product_id')},
        ),
    ]
