# Generated by Django 3.2.5 on 2021-07-18 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0013_alter_cartitem_qty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='total_items',
        ),
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
